<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <ProjectFile Include="$(MSBuildThisFileDirectory)modules\**\*.csproj" />
  </ItemGroup>

  <Target Name="IncludeModuleProjects" BeforeTargets="CollectProjectReferences" Condition="'$(MSBuildProjectName)' == 'ShuRuk.Host'">
    <ItemGroup>
      <ProjectReference Include="@(ProjectFile)" />
    </ItemGroup>
  </Target>
</Project>